-- AlterTable
ALTER TABLE "ContentBlock" ADD COLUMN     "freeHeight" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN     "freeWidth" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN     "freeX" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "freeY" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "freeZIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sectionFreeHeight" INTEGER NOT NULL DEFAULT 400,
ADD COLUMN     "sectionLayoutMode" TEXT NOT NULL DEFAULT 'grid';
